spring.application.name=app-entidad-financiera

# Se completa en la Fase 5 (conexion a PostgreSQL)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true